apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: calculator
spec:
  scaleTargetRef: # HPA can scale a Rollout like a Deployment
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: calculator
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
