apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/part-of: calculator

resources:
  - rollout.yaml
  - services.yaml
  - ingress.yaml
  - analysis-template.yaml
  - servicemonitor.yaml
  - hpa.yaml
  - pdb.yaml
